"""Create Game Model

Revision ID: 283aa106aba4
Revises: faebd12f9523
Create Date: 2025-05-24 10:35:55.739631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283aa106aba4'
down_revision = 'faebd12f9523'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
